DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_osm_cache;
CREATE TABLE /*TABLE_PREFIX*/t_osm_cache (
  pk_i_id INT NOT NULL AUTO_INCREMENT,
  s_query VARCHAR(500),
  d_coord_lat DECIMAL(20, 10),
  d_coord_long DECIMAL(20, 10),
  dt_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (pk_i_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';